### ISSUE TITLE
Can't install on Lollipop

### ISSUE THREAD

**Issue by neheb** [downthecrop/checkra1n-twrp#1]
Using an old HTC One m7 (checkra1n actually works with TWRP here). This app seems to have a minimum of API 23. Lollipop 5.1 uses API 22. Any chance of lowering it?

**Comment by downthecrop** [comment]
https://github.com/downthecrop/checkra1n-twrp/commit/d530617733e12feb6e4257886de181e8fb76f9c8

**Comment by neheb** [comment]
Hmm I still can't install it.

Is this APK 64-bit only? My device is 32-bit.

**Comment by downthecrop** [comment]
Only 64bit as the ZIP is bundled with it. You can rebundle the zip by replacing the 64bit binary with the 32bit ARM release. Would double the bundle size for a very limited number of devices benefiting. https://github.com/downthecrop/checkra1n-twrp/releases/tag/0.10.2
