### ISSUE TITLE
Support for checkra1n 0.12.0 beta

### ISSUE THREAD

**Issue by ghost** [downthecrop/checkra1n-twrp#4]
checkra1n has been updated to support iOS 14.1 and 14.2
Not sure you can update the checkra1n file in the zip with the arm64 one from their site though so would like some advice regarding that though.

**Comment by downthecrop** [comment]
0.12.0 support has [already been added 👍 ](https://github.com/downthecrop/checkra1n-twrp/commit/ab7fffb183d9bf02652a72c3af02ea6c72cd9542)

0.12.0 APK https://github.com/downthecrop/checkra1n-twrp/raw/master/app/release/app-release.apk

0.12.0 beta zips https://github.com/downthecrop/checkra1n-twrp/releases/tag/0.12.0
