### ISSUE TITLE
Worked in an older magisk version, but not a newer one

### ISSUE THREAD

**Issue by nguyenduongngoc** [downthecrop/checkra1n-twrp#6]
It has been working well in Magisk 18.1
But when I updated Magisk to the latest version (22), it stopped working, couldn’t get root access 
For sure, downgrading magisk could help. But it was weird

**Comment by downthecrop** [comment]
Sorry for the late reply but for future refence if anyone comes across this you can enable root for any application in the Majisk Manager app.

![Screenshot_20210523-182748_Magisk](https://user-images.githubusercontent.com/4764745/119284507-b94a4a00-bbf4-11eb-8e3d-8ee584242ac2.png)
