### ISSUE TITLE
Author, are you no longer updating，We need you.

### ISSUE THREAD

**Issue by anjingder** [downthecrop/checkra1n-twrp#9]
Author, are you no longer updating，We need you.

**Comment by SimPilotAdamT** [comment]
How's about I try to update it by forking it?

**Comment by anjingder** [comment]
Cool. Thank you very much. Arm32. Can you make it work,

**Comment by SimPilotAdamT** [comment]
Whoops I'll try

**Comment by downthecrop** [comment]
hey boys. I'll do a 0.12.4 release
